#-Basic info----------------------------------------------------------------------------------------
display_name: ariba_resfinder
name: &name ariba_resfinder__2.1.0__200811
version:
  schema: 2.0
  code: 2.1.0
  resource: 200811
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: sample
  description: >
    This preforms read based mapping against the resfinder DB's. The options show the species entries 
    which will be attempted for mlst with key originating from the species DB. This is done against 
    the cge_db using ariba.
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [resistance]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_ariba_plasmidfinder
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "/bifrost_ariba_resfinder/resources/resfinder/ref_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      paired_reads:
        summary:
          data:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
    - "ariba_resfinder/resistance/report.tsv"
  sample:
    properties:
      resistance:
        summary: 
        component:
          _id: 
          date: "ObjectId"
    report:
      resistance:
        title: Resistance
        info: *name
        columns:  # headers, these values are statically present in datadump
          - {id: "gene", name: "gene"}
          - {id: "coverage", name: "%cov"}
          - {id: "identity", name: "%id"}
          - {id: "variants", name: "# of variants"}
        data: []  # list of dicts parsed in datadump
  sample_component:
    summary:
    results:
      ariba_resfinder/resistance/report.tsv: {}
#---------------------------------------------------------------------------------------------------
